version: '4.47'

services:
  # PostgreSQL
  postgres-db:
    image: postgres:14-alpine
    container_name: ratewatch_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ratewatchdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql@14/data
    restart: unless-stopped

  # Redis
  redis-cache:
    image: redis:7-alpine
    container_name: ratewatch_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data: