version: '4.47'

services:
  # PostgreSQL
  postgres-db:
    image: postgres:14-alpine
    container_name: ratewatch_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ratewatchdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql@14/data
    restart: unless-stopped

  # Redis
  redis-cache:
    image: redis:7-alpine
    container_name: ratewatch_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # Microservices
  authservice:
    container_name: ratewatch_authservice
    build:
      context: ./src/Services/AuthService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=ratewatchdb;Username=admin;Password=secret
      - AppSettings__Token=HelloThisIsMySuperSecretKeyYouCannotGuessWhatThisIsItMustBeLongTryingToMakeItLong
    depends_on:
      - postgres-db

  userservice:
    container_name: ratewatch_userservice
    build:
      context: ./src/Services/UserService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=ratewatchdb;Username=admin;Password=secret
    depends_on:
      - postgres-db
  
  apigateway:
    container_name: ratewatch_apigateway
    build:
      context: ./src/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - authservice
      - userservice

volumes:
  postgres-data:
  redis-data: