apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ratewatch-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.ratewatch.live
    secretName: ratewatch-api-tls
  rules:
  - host: api.ratewatch.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apigateway-service
            port:
              number: 80