apiVersion: apps/v1
kind: Deployment
metadata:
  name: thresholdruleservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thresholdruleservice
  template:
    metadata:
      labels:
        app: thresholdruleservice
    spec:
      containers:
      - name: thresholdruleservice
        image: ghcr.io/bsametarman/ratewatch-thresholdruleservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: Kafka__BootstrapServers
          value: "kafka-service:9092"
        - name: Kafka__GroupId
          value: "threshold-rule-consumer-group"
        - name: Kafka__RatesUpdatedTopic
          value: "rates-updated-topic"
        - name: Kafka__AlertTriggeredTopic
          value: "alert-triggered-topic"
        - name: Redis__ConnectionString
          value: "redis-cache-service:6379"
        - name: Redis__ActiveAlertsKey
          value: "active_alerts"