apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyticsservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyticsservice
  template:
    metadata:
      labels:
        app: analyticsservice
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: analyticsservice
        image: ghcr.io/bsametarman/ratewatch-analyticsservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: Elasticsearch__Uri
          value: "http://elasticsearch-service:9200"
        - name: Kafka__BootstrapServers
          value: "kafka-service:9092"
        - name: Kafka__GroupId
          value: "analytics-consumer-group"
        - name: Kafka__RatesUpdatedTopic
          value: "rates-updated-topic"