name: CD - Deploy to DigitalOcean Kubernetes

on:
  # workflow_run:
  #   workflows: ["CI - Build and Push Docker Images"]
  #   types:
  #     - completed
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DOCR_TOKEN }}

    - name: Set up Kubernetes config
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/apps/
        
    - name: Verify deployments
      run: kubectl rollout status deployment/apigateway-deployment