name: CI - Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build and push AlertService
      uses: docker/build-push-action@v5
      with:
        context: ./src/Services/AlertService
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ratewatch-alertservice:latest

    - name: Build and push ApiGateway
      uses: docker/build-push-action@v5
      with:
        context: ./src/ApiGateway
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ratewatch-apigateway:latest

    - name: Build and push AnalyticsService
      uses: docker/build-push-action@v5
      with:
        context: ./src/Services/AnalyticsService
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ratewatch-analyticsservice:latest
    
    - name: Build and push AuthService
      uses: docker/build-push-action@v5
      with:
        context: ./src/Services/AuthService
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ratewatch-authservice:latest

    - name: Build and push DashboardService
      uses: docker/build-push-action@v5
      with:
        context: ./src/Services/DashboardService
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ratewatch-dashboardservice:latest
    
    - name: Build and push NotificationService
      uses: docker/build-push-action@v5
      with:
        context: ./src/Services/NotificationService
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ratewatch-notificationservice:latest
    
    - name: Build and push RateFetcherService
      uses: docker/build-push-action@v5
      with:
        context: ./src/Services/RateFetcherService
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ratewatch-ratefetcherservice:latest

    - name: Build and push ThresholdRuleService
      uses: docker/build-push-action@v5
      with:
        context: ./src/Services/ThresholdRuleService
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ratewatch-thresholdruleservice:latest

    - name: Build and push UserService
      uses: docker/build-push-action@v5
      with:
        context: ./src/Services/UserService
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ratewatch-userservice:latest